name: RDP via Cloudflare

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Set RDP Password
      run: net user runneradmin P@ssw0rd123

    - name: Install Cloudflared
      run: |
        Invoke-WebRequest https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe -OutFile cloudflared.exe

    - name: Start Cloudflare Tunnel
      run: .\cloudflared.exe tunnel --url tcp://localhost:3389
